### ISSUE TITLE
Nav Links not working

### ISSUE THREAD

**Issue by matto2** [trys/sergey#26]
I tried switching the navigation from standard html to sergy-links, but they did not rendering as links.

**Comment by whyboris** [comment]
Confirming, following the example (and several variations) results in rendered HTML that contains 
```html
<sergey-link to="index.html">Home</sergey-link>
```
rather than:
```html
<a href="index.html">Home</a>
```

**Comment by trys** [comment]
@whyboris Ahh, great spot, thanks for investigating - I'll have a look into it!
